resource "local_file" "group_vars" {
  content = <<-DOC
    ---
    # Ansible group_vars containing variable values from Terraform.
    # Generated by Terraform.
    
    squid_port: 3128
    squid_ip: ${yandex_compute_instance.nginx.network_interface.0.ip_address}
    squid_allowed_list:
      - ${var.subnet1[0]} 
      - ${var.subnet2[0]}
    
    yum_proxy: "http://{{ squid_ip }}:{{ squid_port }}"
    wordpress_proxy: "{{ yum_proxy }}"
    prometheus_proxy: "{{ yum_proxy }}"
    alertmanager_proxy: "{{ yum_proxy }}"
    node_exporter_proxy: "{{ yum_proxy }}"
    wp_proxy_host: "{{ squid_ip }}"
    wp_proxy_port: "{{ squid_port }}"

    domain_name: ${var.mydomain}
    web_resources:
      - name: www
        ip: ${yandex_compute_instance.wordpress.network_interface.0.ip_address}
        port: 80
      - name: gitlab
        ip: ${yandex_compute_instance.gitlab.network_interface.0.ip_address}
        port: 80
      - name: grafana
        ip: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
        port: 3000
      - name: prometheus
        ip: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
        port: 9090
      - name: alertmanager
        ip: ${yandex_compute_instance.monitoring.network_interface.0.ip_address}
        port: 9093

    acme_domain: "{{ domain_name }}"
    acme_resources: "{{ web_resources }}"
    acme_server: "${var.acme_server}"
    
    mysql_master_ip: ${yandex_compute_instance.db01.network_interface.0.ip_address}
    wp_db_host: "{{ mysql_master_ip }}"

    prometheus_nginx_internal_ip: ${yandex_compute_instance.nginx.network_interface.0.ip_address}

    gitlab_runner_coordinator_url: "http://${yandex_compute_instance.gitlab.network_interface.0.ip_address}"

    DOC
  filename = "../ansible/group_vars/all.yml"

  depends_on = [
    yandex_compute_instance.nginx,
    yandex_compute_instance.wordpress,
    yandex_compute_instance.monitoring
  ]
}
