---
- name: install default packages
  become: true
  ansible.builtin.yum:
    name:
      - epel-release
    state: present

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: permissive
